[package]
name = "example"
version = "0.1.0"
authors = ["tanhui <tanhui@corp-ci.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
c123chain-cdk = { path = "../" }
c123chain-cdk-proc = { path = "../proc/" }

[profile.release]
opt-level = "s"
lto = true
